<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Release</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <Target Name="CopyToStaging" AfterTargets="Build">
    <Copy
            SourceFiles="$(IntermediateOutputPath)$(TargetName).dll"
            DestinationFolder="$(ProjectDir)/Staging/patchers"
            SkipUnchangedFiles="true" />
  </Target>
</Project>

